[package]
name = "qec-codes"
version = "0.1.0"
entrypoint = "lib.typ"
repository = "https://github.com/nzy1997/qec-codes"
authors = [
  "Zhongyi Ni <https://github.com/nzy1997>",
  "Jin-Guo Liu <https://github.com/GiggleLiu>"
]
license = "MIT"
description = "A package for drawing quantum error correction codes with Typst."
categories = ["visualization"]
exclude = ["examples/"]